# Site settings
baseURL = "ewanbuckingham.com"
languageCode = "en-gb"
title = "Ewan Buckingham"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "RSS", "sitemap"]
disableHugoGeneratorInject = true

# Local preview mode
relativeURLs = true
uglyURLs = true

# Copyright
copyright = "&copy;2025 Ewan Buckingham"

[services]
  [services.googleAnalytics]
    # Enter your tracking code to enable Google Analytics
    ID = ""

[params]

  # Metadata for search engines and social sharing
  author = "Ewan Buckingham"
  description = "Ewan Buckingham's - a personal website"
  shareImage = "images/social.jpg"
  blueskyHandle = "ewanbuckingham"

  # Whether you purchased the license from the author.
  licensed = false

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/profile_photo.jpg" 
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "Email"
        url = "mailto:ewan@ewanbuckingham.com"
        new_tab = true # new tab

  [[params.links.list1.link]]
        text = "Photography"
        url = "#"
        new_tab = true # new tab


  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Social"
   
      [[params.links.list2.link]]
        text = "Bluesky"
        url = "https://bsky.app/profile/ewanbuckingham.com"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Professional"

      [[params.links.list3.link]]
        text = "LinkedIn"
        url = "https://www.linkedin.com/in/ewan-buckingham-3177b112/"

      [[params.links.list3.link]]
        text = "Github"
        url = "https://github.com/ewanbuckingham"

      
  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split

[server]
[[server.headers]]
    for = '/**'
    [server.headers.values]
      Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' https://dummyimage.com"
      Referrer-Policy = 'strict-origin-when-cross-origin'
      X-Content-Type-Options = 'nosniff'
      X-Frame-Options = 'DENY'
      X-XSS-Protection = '1; mode=block'
